name: Build and Upload Release

on:
  push:
    branches: [master]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.1"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # - name: Build release APK
      #   run: flutter build apk --release

      - name: Build release APK
        uses: subosito/flutter-action@v1.1.1
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          run: echo $KEY_JKS > key.jks && flutter pub get && flutter test && flutter build apk --release

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: Rikedu
          path: build/app/outputs/apk/release/app-release.apk
